[package]
name = "library"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.3.13"
regex = "1"
itertools = "0.10.1"
thiserror = "1.0"
docx-rs = "0.2.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}

[dev-dependencies]
pretty_assertions = "0.1.0"

[profile.release]
panic="abort"
opt-level="z"
lto="fat"
codegen-units=1

[features]
serde_support = []