[package]
name = "library"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
regex = "1"
itertools = "0.10.1"
thiserror = "1.0"
docx-rs = "0.2.0"
# docx = { git = "https://github.com/ManevilleF/docx-rs.git" }

[dev-dependencies]
pretty_assertions = "0.1.0"

[profile.release]
panic="abort"
opt-level="z"
lto="fat"
codegen-units=1
