[package]
name = "library"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1"
thiserror = "1.0"
anyhow = "1.0"
colored = "2"
docx = { git = "https://github.com/ManevilleF/docx-rs.git" }


[dev-dependencies]
pretty_assertions = "0.1.0"

